#include "Rng.h"



int Rng::getRandomInt(int lower_bound, int upper_bound)
{
	std::mt19937 mt(rd());
	std::uniform_int_distribution<int> random(lower_bound, upper_bound);

	return random(mt);
}


//http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution
float Rng::getRandomFloat(float lower_bound, float upper_bound)
{
	std::mt19937 mt(rd());
	std::uniform_real_distribution<> random(lower_bound, upper_bound);

	float return_val;

	for(int transformer_count = 0; transformer_count < 5; transformer_count++)
	{
		//Use random to transform the random unsigned int generated by random into a double/float in [1, 2)
		return_val = float(random(mt));
	}
	return return_val;
}
